level1 = [
    "WWWWWWWWWWWWWWWWWW",
    "WP         WWW   W",
    "WWWWWW WWW WWW W W",
    "WWW    WWW     W W",
    "W    WWWWWWWWW W W",
    "W WWWW     WWWWW W",
    "W WWWW WWW WWWWW W",
    "W  WWW W         W",
    "W  WWW W WWWW WW W",
    "WW WWW W WWWW WWWW",
    "WW     W WK      W",
    "WWWWWWWW WWWWWWWWW",
    "W                W",
    "WWWWW WWWWWW WWWWW",
    "WWWWW   WW   WWWWW",
    "WWWWWDWWWWWWDWWWWW",
    "WWWWW        WWWWW",
    "WWWWWWWWEEWWWWWWWW",
]

level2=[
       "WWWWWWWWWWWWWW",
    "WP         WWW   W",
    "WWW WWW WWW  ",
    "WWW    WWW     W W",
    "W    WWWWW W W",
    "W WWKW     WWWKW ",
    "W WWWW WWW WWWWW",
    "W  WWW          ",
    "W  WWW  WWWW  ",
    "WW WKW WWWW WWWW",
    "WW     WWK      W",
    "WWWWW WWWWWWWWW",
    "WWW              W",
    "WWWWW WWWWWW WWWWW",
    "WWWWW   WW   WWWWW",
    "WWWWWDWWWWWWDWWWWW",
    "WWEWWW        WWEWW",
]

'''
level3= [  "WWWWWWWWWWWW",
    "W         WWW   W",
    "WWWWWW   K WWW WW W W",
    "WWW    WWW     W W",
    "W       WWWWWW W W",
    "W WWKW     WWWKW W",
    "W W  WWWWW W",
    "W  WWW W      P   W",
    "W  WWW W WWWW WW W",
    "WkW WKW W WWWW WWWW",
    "WW     W WK      W",
    "WWWkWWWW WWWWWWWWW",
    "W                W",
    "WWWWW WWWWWW WWWWW",
    "WWWWW   WW   WWWWW",
    "WWWWWDWWWWWWDWWWWW",
    "WWWWW        WWWWW",
    "WWWWWWWWEEWWWWWWWW",
]

level4=["WWWWWWWWWWWWWWWWWW",
    "W       WWW   W",
    "WWWWWW WWW WWW W W",
    "WWW    WWW     W W",
    "W    WWWWkWWWWW W W",
    "W WWKW     WWWKW W",
    "W WWWW WWW WWWWW W",
    "W  W W         W",
    "W  WWW W WWWW WW W",
    "WW WKW W WWWW WWWW",
    "WWE E     W WK      W",
    "WWWWWWWW WWWWWWWWW",
    "W                W",
    "WWWWW WWWWWW WWWWW",
    "WWWWW   WW   WWWWW",
    "WWWWWDWWWWWWDWWWWW",
    "WWWWW        WWWWW",
    "WWWWWWWWWWPWW",
]'''

levels_list=[level1,level2]

#w-walls,d-doors,k-keys,e-exist,p-player
